/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormaButtonType } from "./components/forma-button/forma-button";
export { FormaButtonType } from "./components/forma-button/forma-button";
export namespace Components {
    interface FormaButton {
        /**
          * @default null
         */
        "ariaLabel": string | null;
        /**
          * @default false
         */
        "disabled": boolean;
        "name"?: string;
        /**
          * @default 'button'
         */
        "type": FormaButtonType;
        "value"?: string;
    }
}
declare global {
    interface HTMLFormaButtonElement extends Components.FormaButton, HTMLStencilElement {
    }
    var HTMLFormaButtonElement: {
        prototype: HTMLFormaButtonElement;
        new (): HTMLFormaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "forma-button": HTMLFormaButtonElement;
    }
}
declare namespace LocalJSX {
    interface FormaButton {
        /**
          * @default null
         */
        "ariaLabel"?: string | null;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "name"?: string;
        /**
          * @default 'button'
         */
        "type"?: FormaButtonType;
        "value"?: string;
    }

    interface FormaButtonAttributes {
        "disabled": boolean;
        "type": FormaButtonType;
        "name": string;
        "value": string;
        "ariaLabel": string | null;
    }

    interface IntrinsicElements {
        "forma-button": Omit<FormaButton, keyof FormaButtonAttributes> & { [K in keyof FormaButton & keyof FormaButtonAttributes]?: FormaButton[K] } & { [K in keyof FormaButton & keyof FormaButtonAttributes as `attr:${K}`]?: FormaButtonAttributes[K] } & { [K in keyof FormaButton & keyof FormaButtonAttributes as `prop:${K}`]?: FormaButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "forma-button": LocalJSX.IntrinsicElements["forma-button"] & JSXBase.HTMLAttributes<HTMLFormaButtonElement>;
        }
    }
}
