/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormaButtonAnimation, FormaButtonType, FormaButtonVariant } from "./components/forma-button/forma-button";
export { FormaButtonAnimation, FormaButtonType, FormaButtonVariant } from "./components/forma-button/forma-button";
export namespace Components {
    /**
     * A native button control with Forma variants, colors, and optional motion.
     */
    interface FormaButton {
        /**
          * Overrides the motion selected by the active variant.
         */
        "animation"?: FormaButtonAnimation;
        /**
          * Supplies an accessible name, especially for icon-only buttons.
          * @default null
         */
        "ariaLabel": string | null;
        /**
          * Overrides the variant palette with a valid solid CSS color.
         */
        "color"?: string;
        /**
          * Disables native pointer, keyboard, and form interactions.
          * @default false
         */
        "disabled": boolean;
        /**
          * Sets the name submitted with the button's form value.
         */
        "name"?: string;
        /**
          * Overrides the variant or automatically selected label color.
         */
        "textColor"?: string;
        /**
          * Sets the native button type and defaults to the inert button behavior.
          * @default 'button'
         */
        "type": FormaButtonType;
        /**
          * Sets the value submitted when this button initiates form submission.
         */
        "value"?: string;
        /**
          * Selects the visual button style.
          * @default 'simple'
         */
        "variant": FormaButtonVariant;
    }
}
declare global {
    /**
     * A native button control with Forma variants, colors, and optional motion.
     */
    interface HTMLFormaButtonElement extends Components.FormaButton, HTMLStencilElement {
    }
    var HTMLFormaButtonElement: {
        prototype: HTMLFormaButtonElement;
        new (): HTMLFormaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "forma-button": HTMLFormaButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * A native button control with Forma variants, colors, and optional motion.
     */
    interface FormaButton {
        /**
          * Overrides the motion selected by the active variant.
         */
        "animation"?: FormaButtonAnimation;
        /**
          * Supplies an accessible name, especially for icon-only buttons.
          * @default null
         */
        "ariaLabel"?: string | null;
        /**
          * Overrides the variant palette with a valid solid CSS color.
         */
        "color"?: string;
        /**
          * Disables native pointer, keyboard, and form interactions.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Sets the name submitted with the button's form value.
         */
        "name"?: string;
        /**
          * Overrides the variant or automatically selected label color.
         */
        "textColor"?: string;
        /**
          * Sets the native button type and defaults to the inert button behavior.
          * @default 'button'
         */
        "type"?: FormaButtonType;
        /**
          * Sets the value submitted when this button initiates form submission.
         */
        "value"?: string;
        /**
          * Selects the visual button style.
          * @default 'simple'
         */
        "variant"?: FormaButtonVariant;
    }

    interface FormaButtonAttributes {
        "disabled": boolean;
        "variant": FormaButtonVariant;
        "color": string;
        "textColor": string;
        "animation": FormaButtonAnimation;
        "type": FormaButtonType;
        "name": string;
        "value": string;
        "ariaLabel": string | null;
    }

    interface IntrinsicElements {
        "forma-button": Omit<FormaButton, keyof FormaButtonAttributes> & { [K in keyof FormaButton & keyof FormaButtonAttributes]?: FormaButton[K] } & { [K in keyof FormaButton & keyof FormaButtonAttributes as `attr:${K}`]?: FormaButtonAttributes[K] } & { [K in keyof FormaButton & keyof FormaButtonAttributes as `prop:${K}`]?: FormaButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A native button control with Forma variants, colors, and optional motion.
             */
            "forma-button": LocalJSX.IntrinsicElements["forma-button"] & JSXBase.HTMLAttributes<HTMLFormaButtonElement>;
        }
    }
}
